---
# - include: config-inventory.yml
- include_tasks: install-packages.yml
- include_tasks: security.yml
  when: "{{security_updates | default('false')}}"
- include_tasks: config-users.yml
- include_tasks: config-ssh.yml
- include_tasks: config-code-rade.yml
